baseURL: https://xrmatrix.pages.dev/
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage: en
# language code
languageCode: en-us
title: XR-MATRIX

# publish directory
publishDir: ./publish

# Change the default theme to be use when building the site with Hugo
theme: cactus

permalinks:
  posts: /posts/:title/

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/Arecardo
  twitter: your-twitter-link
  # stackoverflow: your-stackoverflow-link
  # facebook: your-facebook-link

# Site parameters
params:
  # Site Author
  author: Ricardo Zhang
  # Author biography
  bio: Thinking, Creating and Loving
  # Site Description, used in HTML meat
  description: Thinking, Creating and Loving
  hiddenPostSummaryInHomePage: true
  showToc: true
  showAllPostsOnHomePage: true

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
